# Importing numpy

In [3]:
import numpy as np

In [4]:
list = [1,2,3,4,5,6]

# Converting list into array

In [5]:
arr = np.array(list)

In [39]:
print(list)
print(arr)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


# Converting tuple into Array

In [7]:
tuple = (1,2,3,4,5,6)
ar = np.array(tuple)
print(tuple)
print("-------")
print(ar)
print(type(ar))

(1, 2, 3, 4, 5, 6)
-------
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [8]:
num = np.random.randint(50)
num

31

In [9]:
numb =  np.random.rand(10)
numb

array([0.48706767, 0.07715583, 0.59996571, 0.92370955, 0.27306112,
       0.90379904, 0.95890265, 0.44556639, 0.94824043, 0.64457214])

# Creating Matrix

In [10]:
mat = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [11]:
ma = np.array(mat)
ma

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
ma.dtype

dtype('int64')

In [13]:
ma.shape

(4, 3)

In [14]:
ma.ndim

2

# Arange

In [15]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a = np.random.randint(100)
a

30

In [17]:
a = np.random.randn(50)
a

array([ 1.04586155,  0.55741264,  1.37171609,  0.65258124,  0.32867275,
       -1.96475839,  1.5887769 , -0.37878439,  0.05488321, -0.55461534,
        1.2005229 ,  0.01160136,  0.23222078,  1.48127519, -0.23510143,
       -0.24205098, -0.60880403,  0.91126967, -1.07054595, -0.33443414,
        0.13438875,  1.9966205 , -0.30966733, -0.51880013, -1.54733409,
        0.54449922,  2.15517122, -0.88124904,  0.17349721,  0.52804548,
       -0.11497613,  0.02908778,  1.15445479,  0.38516001, -0.7388875 ,
        0.07138542, -0.30069818,  0.45465079,  0.6952236 ,  1.25763866,
        1.34339513,  0.27330852,  1.6997979 ,  1.18401095, -0.28471711,
        0.60118818,  0.89992597,  0.70094212,  0.00913133,  1.92105791])

In [18]:
a.mean()

np.float64(0.35127903116144776)

# Accessing Data 

In [19]:
num = np.arange(1,21)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
num[7]

np.int64(8)

In [21]:
num[3:8]

array([4, 5, 6, 7, 8])

In [22]:
num[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [37]:
a = np.ones(5)
a = np.array(a)
print(a)

[1. 1. 1. 1. 1.]


In [33]:
s = np.zeros(10,int)
s

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
a6 = np.linspace(0,10,6)
print(a6)

[ 0.  2.  4.  6.  8. 10.]


# Reshape

In [42]:
b = [1,2,3,4,5,6]

In [43]:
m = np.array(b)
print(b)
print("----------")
print(m)
print("----------")
print(type(b))
print("----------")
print(type(m))
print("----------")
print(m.shape)

[1, 2, 3, 4, 5, 6]
----------
[1 2 3 4 5 6]
----------
<class 'list'>
----------
<class 'numpy.ndarray'>
----------
(6,)


In [49]:
z = m.reshape((3,2))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
ar = [1,2,3,4,5,6,7,8,9,10,11,12]
ar

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [52]:
a = np.array(ar)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [53]:
arr = a.reshape((4,3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [54]:
arr[0:3,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [58]:
a8 = np.arange(12).reshape(3,4)
a8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
np.ones_like(a8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [67]:
qu = np.identity(5,int)
qu = np.array(qu)
print(qu)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


# RAVEL¶

Ravel is used to reduction of dimensions or flattening the matrix.
converting 2 dim to 1 dim


In [70]:
arra = np.ravel(a8)
print(arra)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


# Transpose

In [71]:
li = [1,2,3,4,5,6,7,8]
ar = np.array(li)
print(ar)

[1 2 3 4 5 6 7 8]


In [74]:
w = ar.reshape(2,4)
w

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
np.transpose(w)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Concatinate

In [76]:
a1 = [1,2,3,4,5]
a2 = [6,7,8,9,10]
aa = np.array(a1)
ab = np.array(a2)
print(aa)
print(ab)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [78]:
v = np.vstack((aa,ab))
v

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [79]:
h = np.hstack((aa,ab))
h

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
a10 = [1,2,3,4,5,6]
a11 = [7,8,9,10,11,12]
ar = np.array(a10)
br = np.array(a11)
arr =ar.reshape((2,3))
brr =br.reshape((2,3))
print(arr)
print(brr)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [88]:
ve = np.vstack((arr,brr))
ve

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [89]:
ho = np.hstack((arr,brr))
ho

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# Basic Mathematical functions

In [90]:
xx = [1,2,3,4,5]
xy = [6,7,8,9,10]
x1 = np.array(xx)
x2 = np.array(xy)
print(x1)
print(x2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [91]:
print(x1+x2)

[ 7  9 11 13 15]


In [92]:
print(x2-x1)

[5 5 5 5 5]


In [93]:
print(x1*x2)

[ 6 14 24 36 50]


In [94]:
print(x1/x2)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [95]:
print(x2/x1)

[6.         3.5        2.66666667 2.25       2.        ]


In [97]:
print(x1**2)

[ 1  4  9 16 25]


In [98]:
print(max(x1))

5


In [99]:
print(min(x2))

6


In [100]:
print(sum(x1))

15


In [101]:
print(sum(x2))

40


In [103]:
print(np.log(x1))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [104]:
print(np.log10(x2))

[0.77815125 0.84509804 0.90308999 0.95424251 1.        ]


In [105]:
print(np.cos(x2))

[ 0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153]


In [106]:
print(np.tan(x2))

[-0.29100619  0.87144798 -6.79971146 -0.45231566  0.64836083]


In [108]:
print(np.sin(x2))

[-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]


# Matrix Maultiplication

In [116]:
r = np.array([[1,2],[4,5]])
s = np.array([[7,8],[10,11]])
print(r)
print(s)

[[1 2]
 [4 5]]
[[ 7  8]
 [10 11]]


In [117]:
matrix = np.matmul(r,s)
matrix

array([[27, 30],
       [78, 87]])

In [118]:
import numpy as np
import time 
import sys